config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root to: 'users#new'

  resources :contacts

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    collection do#collection doはidなどを必要としない固有のルーティングを生成する
      post :confirm
    end
  end

  resources :feeds do
    collection do
      post :confirm
    end
  end

end

app/models/blog.rb
class Blog < ApplicationRecord
  # 下記はアソシエーション。アソシエーション名はそのままメソッドになる。
  belongs_to :user
  # belongs_toかhas_manyで迷ったら、今いるモデルのテーブルのカラムにuser_id,blog_idの様に〜idというのがあったら、belongs_to。
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :title, presence: true
  validates :content, presence: true

  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :edit, :show, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    # Blog.create(title: params[:blog][:title], content: params[:blog][:content])
    # Blog.create(params[:blog])←セキュリティーの問題でエラーが発生するので、下記のようにストロングパラメータを使う
    # Blog.create(params.require(:blog).permit(:title, :content))
    # Blog.create(blog_params)
    # redirect_to "/blogs/new"
    # @blog = Blog.new(blog_params)
    # @blog.user_id = current_user.id #現在ログインしているuserのidを、blogのuser_idカラムに挿入する
    #下記のblogsはmodel/user.rbに定義したアソシエーションのblogsのこと。
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    elsif @blog.save
      # BlogMailer.blog_mail(@blog).deliver
      # @blog = @blog.user.name
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render :new
    end
  end

  def show
    # idを利用してデータを取得する場合は、findメソッドを使う。パラメーターには、idの情報しか送られないため。（title,contentの情報は載っていない）
    # @blog = Blog.find(params[:id])
    # whereは引数の条件に合った値を探し、find_byは条件に一致する最初の値を取得する
    # 詳細を見るボタンを押したブログのid（@blog.id）とfavoritesテーブルのblog_idカラムの値が一致したらそのレコードを@favoritesに代入する
    # もし値が見つからなかったらfind_byメソッドはnilを代入する
    # find_by(title: "タイトルA")
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)

    @comments = @blog.comments
    @comment = @blog.comments.build
  end

  def edit
    # @blog = Blog.find(params[:id])
  end

  def update
    # @blog = Blog.find(params[:id])
    # updateに引数(parametersで参照したもの）を与えると、その引数の値で更新できます。
    if @blog.update(blog_params)
      redirect_to blogs_path ,notice: "ブログを更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    # @blog = Blog.new(blog_params)
    # @blog.user_id = current_user.id
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def login_check
    unless logged_in?
      flash[:alert] = "ログインしてください"
      redirect_to new_session_path
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
<%# hidden_fieldにしないとparameterが送れない。hidden_fieldは値を保持したまま、ビューで内容を隠してくれる。絶対必要！ %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>
<table>
  <tr>
    <th>user_id</th>
    <th>名前</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <!-- 下記のuserはアソシエーションで定義したuserのこと。model/blog.rb -->
    <td><%= blog.user_id %></td>
    <td><%= blog.user.name %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to '詳細を確認する', blog_path(blog.id) %><td>
    <td><%= link_to 'ブログを編集する', edit_blog_path(blog.id) ,data: { confirm: '本当に編集していいですか？'}%></td>
    <td><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>

  <%= link_to '編集', edit_blog_path(@blog) %>
<% end %>
  <p>コメント一覧（ここから下の内容が重要）</p>
  <!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
  <div id="comments_area">
    <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
    <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
  </div>
  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
  <%= link_to '戻る', blogs_path %>