config/routes.rb
Rails.application.routes.draw do

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root to: 'users#new'

  resources :contacts

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    collection do#collection doはidなどを必要としない固有のルーティングを生成する
      post :confirm
    end
  end

  resources :feeds do
    collection do
      post :confirm
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  # パスワードをハッシュ化する。
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # 下記はアソシエーション。アソシエーション名（ここでいうとblogs）はメソッドになる。
  has_many :blogs
  has_many :favorites, dependent: :destroy 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_digest)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">Bootstrap</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sign up</a>
      </div>
      <div id="gnavi">
        <ul class="menu">
          <li><%= f.label :name %></li>
          <li><%= f.text_field :name %></li>
          <li><%= f.label :email %></li>
          <li><%= f.email_field :email %></li>
          <li><%= f.label :password %></li>
          <li><%= f.password_field :password %></li>
          <li><%= f.label :password_confirmation %></li>
          <li><%= f.password_field :password_confirmation %></li>
          <li><%= f.submit "Create my account", class: 'btn btn-success' %></li>
        </ul>
      </div>
    </div>
  </nav>
<!-- <ul class="signup">
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>
  <li><%= f.label :email %></li>
  <li><%= f.email_field :email %></li>
  <li><%= f.label :password %></li>
  <li><%= f.password_field :password %></li>
  <li><%= f.label :password_confirmation %></li>
  <li><%= f.password_field :password_confirmation %></li>
  <li><%= f.submit "Create my account", class: 'btn btn-success' %></li>
</ul> -->
  <%# <%= f.label :name %>
  <%# <%= f.text_field :name %>
  <%# <%= f.label :email %>
  <%# <%= f.email_field :email %>
  <%# <%= f.label :password %>
  <%# <%= f.password_field :password %>
  <%# <%= f.label :password_confirmation %>
  <%# <%= f.password_field :password_confirmation %>
  <%# <%= f.submit "Create my account", class: 'btn btn-success' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to '新しくブログを投稿する', new_blog_path %>
<%= link_to "みんなの投稿を見る", blogs_path %>